import QtQuick
import Shadcn

// A nested Menu is a submenu: the submenu trigger item is auto-generated by Menu.delegate (styled MenuItem + right-side chevron),
// the trigger text comes from the submenu's title; the submenu panel inherits the popover style.
Button {
    id: trigger
    text: qsTr("Open")
    variant: Button.Outline
    trailingIconName: "chevron-down"
    onClicked: menu.popup(0, trigger.height + 4)

    Menu {
        id: menu

        MenuItem { text: qsTr("Team") }

        Menu {
            title: qsTr("Invite users")

            MenuItem { text: qsTr("Email") }
            MenuItem { text: qsTr("Message") }

            Menu {
                title: qsTr("More options")
                MenuItem { text: qsTr("Calendly") }
                MenuItem { text: qsTr("Slack") }
                MenuSeparator {}
                MenuItem { text: qsTr("Webhook") }
            }

            MenuSeparator {}
            MenuItem { text: qsTr("Advanced...") }
        }

        MenuItem { text: qsTr("New Team"); shortcut: "⌘+T" }
    }
}
